### ISSUE TITLE
Must change settings.ini.php manually if upgrading in DEVELOP

### ISSUE THREAD

**Issue by seanvree** [mescon/Muximux#104] opened 2016-12-31 17:46 UTC
windows 10E
IIS 10
PHP/FAST CGI
DEVELOP:  042ce3a7d36dec3d9acde27b57f8a271113e058a

so, I have a python script that updates all my app python apps on windows. and since there have been many updates in the develop branch I'm not sure where the problem started. 

However, I wasn't able to access the index.PHP from LOCALHOST, it kept crashing, found out that the old config looked like this:

[SabNzbd(NZBs)]
name = "SabNzbd(NZBs)"
url = "https://EXAMPLE.com/sabnzb"
scale = 0.1
icon = "muximux-cloud-download"
color = "#000"
enabled = "true"

But you MUST convert them manually to THIS:

[SabNzbd(NZBs)]
name = "SabNzbd(NZBs)"
url = "https://EXAMPLE.com/sabnzb"
icon = "muximux-cloud-download"
color = "#3f8927"
enabled = "true"
landingpage = "false"
dd = "false"

if you don't, the app won't load and you'll get a HTML 500

Not sure if that was meant to happen, but there are prob a lot of people out there who auto-updated and are now crashing. 

thanx for the hard work on this!  LOVING DEVELOP!!

**Comment by mescon** [comment] 2016-12-31 18:09
Hey - we're working it out currently (or rather, @d8ahazard is).
We're squashing the final bugs and will make sure to get this too, before we release version 2.0.

**Comment by seanvree** [comment] 2016-12-31 18:40
No prob, just wanted you guys to know! Thanks for the hard work!

**Comment by d8ahazard** [comment] 2016-12-31 19:36
Sean, if you could please, try *removing* the landingpage and dd sections you added (maybe make a copy of the original first) - do a git pull to the latest version or update through the app and try again.  I don't have those in any of my settings items, and they still work with no issue.  

Most of my apps look like so in settings:

[Plexrequests]
name = "PlexRequests"
url = "https://github.com/lokenx/plexrequests-meteor"
scale = 1
icon = "muximux-people"
color = "#f1c232"
enabled = "true"

I just want to rule out any potential that it's the commit you're currently on, I may have fixed this issue already.

**Comment by seanvree** [comment] 2016-12-31 19:44
@d8ahazard  - I already fixed them all and I didn't save an old copy. I think it was the SCALE if I had to guess.   

But when my box auto updated on one of the new versions "yesterday" it added the DD and landing page items and REMOVED the scale entry on the default config.  however, it didn't update my .ini file, so that's what broke it.  All I did was rename my .ini file and then use the default one that came with the pull, and that's where I saw the difference in the code.  I don't think there's a way for me to find out which version it was because of the way I have my box auto-updating thru a python script.   I'd have to revert back  and reimport the old settings for each commit that was released yesterday which is too much work for me right now! HA! If you get stuck later, LMK and I can help out.

**Comment by d8ahazard** [comment] 2016-12-31 21:06
@seanvree - I get what you're saying.  It's just difficult to tell without being able to reproduce the issue.  Parsing the settings.ini should be smart enough now where every value it looks for has a default in place to avoid loading issues - so if you're looking for the "enabled" setting, it reads the config for a boolean for that value, and if it doesn't exist, should return "true" regardless.  

Hence the difficulty in recreating exactly what the problem is.  I just double-checked that everything gets a default setting, and didn't find anything major.  Made a small commit to address the things I did find - but they weren't anything related to what you're saying here.  

Gonna mark this as closed as I can't recreate w. the current codebase.  We can re-open if any other isues like this arise.

**Closed by d8ahazard** 2016-12-31 21:06 UTC
Labels: bug

**Comment by seanvree** [comment] 2017-01-01 00:16
Yeah, all good man. I'll try to keep an eye on it.  I opened this just so you guys knew there was some type of an issue. 

Like I said, good work!
