### ISSUE TITLE
Unable to use chromecast in Plex inside of Muximux

### ISSUE THREAD

**Issue by djs4000** [mescon/Muximux#83] opened 2016-09-29 05:57 UTC
The chromecast extension in chrome recently updated and I have lost the ability to cast from Plex while using Muximux. Still works fine if I launch Plex in its own window, but I have tested it on 2 computers and the both have the same issue.
Running the latest release of Muximux, Chrome version 53.0.2785.116 m and Plex 1.0.3.2461

**Comment by jaredbidlow** [comment] 2016-10-06 15:49
I am using the built-in cast support in Chrome. I had casting in Muximux working yesterday, but now the cast icon in Plex does not appear to do anything when I click on it. Works fine in Plex on its own

**Comment by jaredbidlow** [comment] 2016-10-06 15:55
Further testing and it casts in muximux by playing a stream and clicking cast from the chrome menu. I'm using Chromecast Audio but assume video would work
So the issue is that while in Muximux, the Plex cast icon breaks/becomes unresponsive.

**Comment by mescon** [comment] 2016-11-20 15:29
Sounds annoying, but I'm not sure there is anything we can do from Muximux to fix the problem.
Input from others is appreciated - I'll leave this open, hoping for feedback.

**Comment by d8ahazard** [comment] 2016-11-26 15:43
@jaredbidlow @djs4000 - Are you linking to the local instance of Plex, or to plex.tv/web/app?  Also, are you using HTTP or HTTPS?  

I just did a quick test.  I am using HTTP, and my Plex instance is on another server in my local network.  Muximux is hosted on my Synology diskstation.  I also have a reverse proxy set up so plex is it's own vhost under http://plex.MYDOMAIN.com.  See below:

https://drive.google.com/open?id=0B0OpOqUNqeKkR3FaMWVKMU9MWkk

So, it's possible that you could be hitting a https-http issue, or you need a vhost reverse proxy to your plex server, or it could be something entirely different.  Knowing more about your setup will be the first step in determining if this is an issue with muximux, your setup, or Plex itself.

**Comment by mescon** [comment] 2016-12-29 05:40
OP has not responded in a month. Closing.

**Closed by mescon** 2016-12-29 05:40 UTC
Labels: help wanted

**Comment by jacobblock** [comment] 2017-06-14 02:08
I know this is closed but I have the same issue with casting. I do not even get the "Cast to" popup. Also possibly related in chrome I have problems reading PDFs using the default in-chrome pdf viewer when trying to view the PDFs under a muximux iframe. I do not have this PDF viewing issue in Firefox. Perhaps some issue with the chrome iframe sandbox?

Happy to provide any feedback. Regarding your questions @d8ahazard, my server is FreeNAS; Plex and Muximux are both running in the same FreeBSD jail. I do not have any reverse proxy, just different ports. Only HTTP, and only connecting to a local instance.

Muximux: 192.168.1.3:80
Plex: 192.168.1.3:32400/web
